feat: fiat price for denom
Local-Money/localmoney pull request #113
Opened 2022-11-16 12:07 UTC by samb-local

taks: LOCAL-784

2022-11-17 13:34 UTC, davirds requested changes

2022-11-17 13:34 UTC, davirds commented on contracts/contracts/price/src/contract.rs
> +    let atom_usd_price = kq.query_exchange_rate("ATOM".to_string()).unwrap();
we can put the "ATOM" in a const

2022-11-17 13:34 UTC, davirds commented on contracts/contracts/price/src/test.rs
> +fn test() {
what is it testing?

2022-11-17 13:34 UTC, davirds commented on contracts/packages/protocol/src/hub_utils.rs
> +pub fn get_hub_config<T: CustomQuery>(deps: Deps<T>) -> HubConfig {
Do we need to use `generics` here?

2022-11-17 13:34 UTC, davirds commented on contracts/packages/protocol/src/offer.rs
> +    pub fn query_by<T: CustomQuery>(
Do we need to use `generics` here?

2022-11-17 13:34 UTC, davirds commented on contracts/packages/protocol/src/offer.rs
> +pub fn load_offer<T: CustomQuery>(
Do we need to use `generics` here?

2022-11-17 13:34 UTC, davirds commented on contracts/packages/protocol/src/price.rs
> +pub fn query_fiat_price_for_denom<T: CustomQuery>(
Do we need to use `generics` here?

2022-11-17 13:34 UTC, davirds commented on contracts/packages/protocol/src/profile.rs
> +pub fn load_profile<T: CustomQuery>(
Do we need to use `generics` here?

2022-11-17 13:34 UTC, davirds commented on contracts/packages/protocol/src/profile.rs
> +pub fn load_profiles<T: CustomQuery>(
Do we need to use `generics` here?

2022-11-18 13:56 UTC, samb-local commented on contracts/contracts/trade/src/contract.rs
> +fn register_hub<T: CustomQuery>(
Yes, because this method is called from the Price contract which implements the KujiraQuerier.

2022-11-18 13:59 UTC, samb-local commented on contracts/contracts/trade/src/contract.rs
> +fn query_trade<T: CustomQuery>(env: Env, deps: Deps<T>, id: String) -> StdResult<TradeInfo> {
Yes, because this method queries the HubCfg which needs the generics because of its relation with the Price contract.

2022-11-18 22:00 UTC, davirds approved these changes
LGTM!

2022-11-18 22:00 UTC, merged