fix: input component
Local-Money/localmoney pull request #153
Opened 2023-01-26 22:31 UTC by samb-local

LOCAL-872

2023-01-27 13:41 UTC, davirds commented
@samb-local it looks like the refresh is not updating the fiat input, only the `1 KUJI = ARS 3860.97` on the top of the card.

<img width="1250" alt="Screen Shot 2023-01-27 at 10 38 17 AM" src="https://user-images.githubusercontent.com/8014901/215100473-0acc6bfc-239b-461c-ac62-04049d6a32ba.png">

2023-01-27 13:46 UTC, davirds commented
@samb-local when I delete the value in crypto and click outside the field, it keeps the value in fiat and leaves the `open trade` button enabled. When I click the `open trade` button it shows me an error on the screen.

![Screen Shot 2023-01-27 at 10 42 49 AM](https://user-images.githubusercontent.com/8014901/215101824-ff1117cb-0976-45f2-aadd-e7b334d6a23a.png)

2023-01-27 14:00 UTC, davirds commented
@samb-local in the `My Offers`, when you try to edit an offer it show the value wrong.

before click edit:
![Screen Shot 2023-01-27 at 10 57 41 AM](https://user-images.githubusercontent.com/8014901/215104649-3eaab778-b507-4684-821e-fccd7b9e3229.png)
after click edit:
![Screen Shot 2023-01-27 at 10 57 49 AM](https://user-images.githubusercontent.com/8014901/215104682-3276788f-165f-4ad2-a097-3a6921ba915f.png)

2023-01-27 14:40 UTC, davirds requested changes
The code looks ok to me, I'm adding only some questions and improvements.

2023-01-27 22:11 UTC, samb-local commented
> @samb-local it looks like the refresh is not updating the fiat input, only the `1 KUJI = ARS 3860.97` on the top of the card.
> 
> <img alt="Screen Shot 2023-01-27 at 10 38 17 AM" width="1250" src="https://user-images.githubusercontent.com/8014901/215100473-0acc6bfc-239b-461c-ac62-04049d6a32ba.png">

fixed at https://github.com/Local-Money/localmoney/pull/153/commits/6e880c9eae7a177478c3568dfa7ff7eb50b7f9ea

2023-01-27 22:28 UTC, samb-local commented
> @samb-local when I delete the value in crypto and click outside the field, it keeps the value in fiat and leaves the `open trade` button enabled. When I click the `open trade` button it shows me an error on the screen.
> 
> ![Screen Shot 2023-01-27 at 10 42 49 AM](https://user-images.githubusercontent.com/8014901/215101824-ff1117cb-0976-45f2-aadd-e7b334d6a23a.png)

fixed at https://github.com/Local-Money/localmoney/pull/153/commits/61b03d29498f27ea963a4ab4b81cfc7a0461279f

2023-01-27 22:29 UTC, samb-local commented on app/yarn.lock
> +  resolved "https://registry.npmjs.org/vue-currency-input/-/vue-currency-input-2.5.1.tgz"
fixed at https://github.com/Local-Money/localmoney/commit/6e880c9eae7a177478c3568dfa7ff7eb50b7f9ea

2023-01-27 22:39 UTC, samb-local commented on app/src/ui/components/CurrencyInput.vue
> +const props = defineProps([
fixed at https://github.com/Local-Money/localmoney/pull/153/commits/5c75ce82614695df130622f1f9a19f45001d6cd4

2023-01-27 22:39 UTC, samb-local commented on app/src/ui/components/CurrencyInput.vue
> +<script setup>
fixed at https://github.com/Local-Money/localmoney/pull/153/commits/5c75ce82614695df130622f1f9a19f45001d6cd4, it's `lang="ts"` actually. 👍🏽

2023-01-28 00:40 UTC, samb-local commented
> @samb-local in the `My Offers`, when you try to edit an offer it show the value wrong.
> 
> before click edit: ![Screen Shot 2023-01-27 at 10 57 41 AM](https://user-images.githubusercontent.com/8014901/215104649-3eaab778-b507-4684-821e-fccd7b9e3229.png) after click edit: ![Screen Shot 2023-01-27 at 10 57 49 AM](https://user-images.githubusercontent.com/8014901/215104682-3276788f-165f-4ad2-a097-3a6921ba915f.png)

Fixed with other formatting issues at: https://github.com/Local-Money/localmoney/pull/153/commits/c71518ebc42fc750698be8776fae1c1e3a4d5f32

2023-01-30 13:34 UTC, davirds approved these changes
LGTM!

2023-01-30 13:36 UTC, merged